# ARRAY


In [6]:
import numpy as np
x = np.array([1, 2, 3 ,4 ])
print(x)


[1 2 3 4]


In [30]:
l=[]
for i in range(1,5):
    int1 = int(input('enter the array element:'))
    l.append(int1)
print(np.array(l))

    


enter the array element: 2
enter the array element: 3
enter the array element: 4
enter the array element: 5


[2 3 4 5]


In [8]:
x=[1,2,3,4]
y=np.array(x)
print(y)
print(y.ndim)

[1 2 3 4]
1


In [12]:
y=np.array([[1,2,3,4],[5,6,7,8]])
print(y)
print(y.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [16]:
ar3 = np.array([[[1,2,3,4],[5,6,7,1],[8,9,0,1]]])
print(ar3)
print(ar3.ndim)


[[[1 2 3 4]
  [5 6 7 1]
  [8 9 0 1]]]
3


In [20]:
arn = np.array([1,2,3,4],ndmin=10)
print(arn)


[[[[[[[[[[1 2 3 4]]]]]]]]]]


### Creating numpy array using numby fxn

### Zeros

In [48]:
arr = np.zeros(5)
arr1 = np.zeros((3,4))
print(arr)
print()
print(arr1)

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### ones


In [53]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [55]:
### empty array(by defualt takes the recently created value)

In [63]:
ar_emp =np.empty(4)
print(ar_emp)

[1. 1. 1. 1.]


### array with range of elements

In [68]:
ar_ran = np.arange(4)
print(ar_ran)


[0 1 2 3]


In [76]:
ar_ran = np.arange(1,10,2)
print(ar_ran)

[1 3 5 7 9]


### diagnoal element one

In [81]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [85]:
ar_dia = np.eye(4,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


### array with linear space

In [94]:
ar_spc = np.linspace(1,20,5)
print(ar_spc)

[ 1.    5.75 10.5  15.25 20.  ]


### creating numpy array using random number


### rand()

In [98]:
var = np.random.rand(4)
print(var)

[0.28490752 0.27114567 0.50340823 0.80606326]


### randn()

In [101]:
var_1 = np.random.randn(5)
print(var_1)


[ 1.02955445  0.28448405 -0.49705084  0.13757258  0.07052814]


### ranf()

In [104]:
var_2 = np.random.ranf(3)
print(var_2)

[0.29634448 0.56960961 0.23099893]


### randint()

In [107]:
var_3 = np.random.randint(1,10,5)
print(var_3)

[6 4 2 1 1]


### Data Types

In [122]:
var = np.array([1,2,3,4])
print('data type:',var.dtype)

data type: int32


In [126]:
var = np.array([1.,2.,3.,4.])
print('data type:',var.dtype)

data type: float64


In [128]:
var = np.array(['a','b','c','d'])
print('data type:',var.dtype)

data type: <U1


In [130]:
var = np.array([1,2,3,4],dtype = np.int8)

print('data type:',var.dtype)

data type: int8


In [132]:
var = np.array([1,2,3,4],dtype = 'f')
print('data type:',var.dtype)

data type: float32


In [134]:
var = np.array([1,2,3,4])
new = np.float32(var)
print('data type:',var.dtype)
print('data type:',new.dtype)
print(var)
print(new)


data type: int32
data type: float32
[1 2 3 4]
[1. 2. 3. 4.]


In [138]:
var1 = np.array([1,2,3,4])
new_1 = var1.astype(float)
print(var1)
print(new_1)


[1 2 3 4]
[1. 2. 3. 4.]


### Arithmetic operation

In [144]:
var = np.array([1,2,3,4])
var1 = var + 3
print(var1)


[4 5 6 7]


In [146]:
var = np.array([1,2,3,4])

print(np.add(var,2))

[3 4 5 6]


In [148]:
var = np.array([[1,2,3],[4,5,6]])
print(np.add(var,3))


[[4 5 6]
 [7 8 9]]


### Aritmetic fxn

In [157]:
var = np.array([7,8,9,0])
print(np.min(var),np.argmin(var))
print(np.max(var),np.argmax(var))


0 3
9 2


In [159]:
var = np.array([7,8,9,0])
print(np.sin(var))
print(np.cos(var))
print(np.sqrt(var))
print(np.cumsum(var))


[0.6569866  0.98935825 0.41211849 0.        ]
[ 0.75390225 -0.14550003 -0.91113026  1.        ]
[2.64575131 2.82842712 3.         0.        ]
[ 7 15 24 24]


In [167]:
var = np.array([[1,2,3],[4,5,6]])
print(np.min(var,axis =0))
var = np.array([[1,2,3],[4,5,6]])
print(np.min(var,axis =1))

[1 2 3]
[1 4]


## shape

In [170]:
var = np.array([5,6,7,8])
print(var.shape)

(4,)


In [176]:
var = np.array([[1,2,3],[4,5,6]])
print(var)
print(var.ndim)
print(var.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [180]:
var = np.array([1,2,3,4],ndmin = 4)
print(var)
print(var.ndim)
print(var.shape)

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


## Reshape

In [188]:
var = np.array([1,2,3,4,5,6])
print(var)
x= var.reshape(3,2)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
2


### coverting 1d to 3d and 3d back to 1d 

In [193]:
var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var)
x= var.reshape(2,3,2)
print(x)
print(x.ndim)

y= x.reshape(-1)
print(y)
print(y.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
