# ARRAY


In [6]:
import numpy as np
x = np.array([1, 2, 3 ,4 ])
print(x)


[1 2 3 4]


In [30]:
l=[]
for i in range(1,5):
    int1 = int(input('enter the array element:'))
    l.append(int1)
print(np.array(l))

    


enter the array element: 2
enter the array element: 3
enter the array element: 4
enter the array element: 5


[2 3 4 5]


In [8]:
x=[1,2,3,4]
y=np.array(x)
print(y)
print(y.ndim)

[1 2 3 4]
1


In [12]:
y=np.array([[1,2,3,4],[5,6,7,8]])
print(y)
print(y.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [16]:
ar3 = np.array([[[1,2,3,4],[5,6,7,1],[8,9,0,1]]])
print(ar3)
print(ar3.ndim)


[[[1 2 3 4]
  [5 6 7 1]
  [8 9 0 1]]]
3


In [20]:
arn = np.array([1,2,3,4],ndmin=10)
print(arn)


[[[[[[[[[[1 2 3 4]]]]]]]]]]


### Creating numpy array using numby fxn

### Zeros

In [48]:
arr = np.zeros(5)
arr1 = np.zeros((3,4))
print(arr)
print()
print(arr1)

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### ones


In [53]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [55]:
### empty array(by defualt takes the recently created value)

In [63]:
ar_emp =np.empty(4)
print(ar_emp)

[1. 1. 1. 1.]


### array with range of elements

In [68]:
ar_ran = np.arange(4)
print(ar_ran)


[0 1 2 3]


In [76]:
ar_ran = np.arange(1,10,2)
print(ar_ran)

[1 3 5 7 9]


### diagnoal element one

In [81]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [85]:
ar_dia = np.eye(4,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


### array with linear space

In [94]:
ar_spc = np.linspace(1,20,5)
print(ar_spc)

[ 1.    5.75 10.5  15.25 20.  ]
